/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.taobao.timetunnel.thrift.router;


public class Constants {

  public static final String LOCAL_HOST = "host";

  public static final String TYPE = "type";

  public static final String RECVWINSIZE = "size";

  public static final String TIMEOUT = "timeout";

  public static final String SUBSCRIBER = "subscriber";

}
